# Site settings
title: General Assembly-Data Science 13
email1: dave@scaleanalytics.com
email2: ed@homejoy.com
description: > # this means to ignore newlines until "baseurl:"
  Content and materials and other synonyms for the GA Data Science NYC Fall Course
# Switch base urls if you are working locally. Top one is for github.
baseurl: "/data-science-course"
#baseurl: ""
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
